### ISSUE TITLE
Default api_spec_file location could be openapi.yaml

### ISSUE THREAD

**Issue by philsturgeon** [membrane-php/membrane-laravel#17]
The README makes it sound like publishing the config is just about updating defaults, but really its required for the main use case unless you happen to have a `api/pets.yaml`. 

```php
# config/membrane.php

    'api_spec_file' => base_path() . '/api/pets.yaml',
```

Could this be a reasonable default like `api/openapi.yaml`? That would then work out of the box for a lot more people, especially as OAS recommends `openapi.yaml` as the filename, then the only issue is what folder is it in, and api isn't an unreasonable one.

**Comment by charjr** [comment]
I agree, will implement that shortly
